### ISSUE TITLE
Consider reverting the deprecation of `*SECP256K1` family of functions

### ISSUE THREAD

**Issue by ribasushi** [Zondax/ledger-filecoin-go#28]
This library is eventually expected to support [`BLS` signatures](https://github.com/LedgerHQ/ledger-secure-sdk/blob/master/include/ox_bls.h). The rename committed in [this PR](https://github.com/Zondax/ledger-filecoin-go/pull/16/files#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dR146) is conflicting with such a future.

Further conversation with @Stebalien: https://github.com/Zondax/ledger-filecoin-go/pull/16#issuecomment-2105958906

:link: [zboto Link](https://app.clickup.com/t/8694jxdp5)

**Comment by raynaudoe** [comment]
Hi @ribasushi, are you suggesting that all crypto primitives should have the curve name appended, as they did before the mentioned PR, right ?

**Comment by ftheirs** [comment]
Hi @ribasushi, at the moment, the devices don't support BLS. However, the main idea was to have a more generic way of interacting with the device. Instead of having multiple signCurve1, signCurve2, ... signCurveN, we can send the curve as a parameter to the sign command. This should also simplify usage for less technical users who may not know about curves or might wonder what SECP256k1 means.

**Comment by emmanuelm41** [comment]
@ribasushi Thir PR #35 should solve this issue. I would like to have your opinion here, before merging.
